name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
    steps:
      - name: 'Generate Release Tag'
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
      - name: 'Create Release'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: 'Upload Linux Binary'
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: range_randomizer
        asset_name: range_randomizer
        asset_content_type: 
  build-windows:
    runs-on: windows-latest
    needs: release
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make OUTPUT=range_randomizer.exe
    - name: 'Upload Windows Binary'
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: range_randomizer.exe
        asset_name: range_randomizer.exe
        asset_content_type: application/octet-stream
